# S02 T04: Pràctica amb programació numèrica #

Familiaritza't amb la Programació Numèrica a través de la llibreria NumPy.

## Nivell 1 ##

### - Exercici 1 ###

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [115]:
import numpy as np

def printStatisticsOfArray(arr):
    print("shape:",arr.shape)
    print("len:",len(arr))
    print("ndim:",arr.ndim)
    print("size:",arr.size)
    print("dtype:",arr.dtype)
    print("sum:",arr.sum())
    print("min:",arr.min())
    print("max:",arr.max())
    print("media:",arr.mean())
    print("Correlation coefficient:",np.corrcoef(arr))
    print("Standard deviation:",np.std(arr))
    if arr.ndim > 1:
        print("Error, this array have two or more dimensions")
    
arr = np.array([1,5,2,3])

printStatisticsOfArray(arr)

shape: (4,)
len: 4
ndim: 1
size: 4
dtype: int32
sum: 11
min: 1
max: 5
media: 2.75
Correlation coefficient: 1.0
Standard deviation: 1.479019945774904


### - Exercici 2 ###

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [65]:
quadrat = np.random.randint(0, 100, size=(3, 3))
print(quadrat)

[[73 56 49]
 [ 6 91 87]
 [51 60  9]]


### - Exercici 3 ###

Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [67]:
print(quadrat)
print("Total columnas:",quadrat.sum(axis=0))
print("Total filas:",quadrat.sum(axis=1))

[[73 56 49]
 [ 6 91 87]
 [51 60  9]]
Total columnas: [130 207 145]
Total filas: [178 184 120]


### - Exercici 4 ###

Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [167]:
x = np.array([33,45,56,56,27,58,47])
y = np.array([150,180,200,180,150,180,180])

def coefCorrPearson(x,y):
    n=x.size
    sumX = x.sum()
    xQuadrat = x**2
    sumxQuadrat = xQuadrat.sum()
    sumY = y.sum()
    yQuadrat = y**2
    sumyQuadrat = yQuadrat.sum()
    xy = x*y
    sumXY = xy.sum()
    primero = (n*sumXY)-((sumX)*(sumY))
    raizX = (n*(sumxQuadrat)-((sumX)**2))**(1/2)
    raizY = (n*(sumyQuadrat)-((sumY)**2))**(1/2)
    r=(primero)/((raizX)*(raizY))
    
    return r

print("r = {0:.2f}".format(coefCorrPearson(x,y)))

print(np.corrcoef(x,y))


r = 0.88
[[1.         0.88270465]
 [0.88270465 1.        ]]
