# S02 T04: Pràctica amb programació numèrica #

Familiaritza't amb la Programació Numèrica a través de la llibreria NumPy.

## Nivell 1 ##

### - Exercici 1 ###

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [200]:
import numpy as np

def printStatisticsOfArray(arr):
    print("ndim:",arr.ndim)
    print("len:",len(arr))
    print("size:",arr.size)
    print("dtype:",arr.dtype)
    print("\nMeasures of Central Tendency")
    
    print("media:",np.mean(arr))
    print("mediana",np.median(arr))
    print("\nMeasures of Dispersion")
    
    print("max:",np.amax(arr))
    print("min:",np.amin(arr))
    print("range:",np.ptp(arr))
    print("variance:",np.var(arr))  
    print("Correlation coefficient:",np.corrcoef(arr))
    print("Standard deviation:",np.std(arr))
        
    if arr.ndim > 1:
        print("Error, this array have two or more dimensions")
    
arr = np.array([1,5,2,3])



printStatisticsOfArray(arr)

ndim: 1
len: 4
size: 4
dtype: int32

Measures of Central Tendency
media: 2.75
mediana 2.5

Measures of Dispersion
max: 5
min: 1
range: 4
variance: 2.1875
Correlation coefficient: 1.0
Standard deviation: 1.479019945774904


### - Exercici 2 ###

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [195]:
def quadrat(n):
    size=(n, n)
    quadrat = np.random.randint(0, 100, size)    
    return quadrat

n=3
quadrat = quadrat(n)
print(quadrat)

[[63 17  4]
 [17 41 88]
 [94 37 10]]


### - Exercici 3 ###

Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [198]:
print(quadrat)

def sumaValorsMatriu(quadrat):
    totalColumnas = quadrat.sum(axis=0)
    totalFilas = quadrat.sum(axis=1)
    
    return totalColumnas,totalFilas

totalColumnas, totalFilas = sumaValorsMatriu(quadrat)
print("Total columnas:",totalColumnas)
print("Total filas:",totalFilas)

[[63 17  4]
 [17 41 88]
 [94 37 10]]
Total columnas: [174  95 102]
Total filas: [ 84 146 141]


### - Exercici 4 ###

Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [199]:
x = np.array([33,45,56,56,27,58,47])
y = np.array([150,180,200,180,150,180,180])

def coefCorrPearson(x,y):
    n=x.size
    sumX = x.sum()
    xQuadrat = x**2
    sumxQuadrat = xQuadrat.sum()
    sumY = y.sum()
    yQuadrat = y**2
    sumyQuadrat = yQuadrat.sum()
    xy = x*y
    sumXY = xy.sum()
    primero = (n*sumXY)-((sumX)*(sumY))
    raizX = (n*(sumxQuadrat)-((sumX)**2))**(1/2)
    raizY = (n*(sumyQuadrat)-((sumY)**2))**(1/2)
    r=(primero)/((raizX)*(raizY))
    
    return r

print("r = {0:.2f}".format(coefCorrPearson(x,y)))

print(np.corrcoef(x,y))


r = 0.88
[[1.         0.88270465]
 [0.88270465 1.        ]]
